### ISSUE TITLE
Percolation_sim function not working

### ISSUE THREAD

**Issue by Shannon2673** [Shannon2673/Computational_Final#2]
After writing the simulation for the groundwater percolation lattice, I moved the code into a function percolation_sim, to streamline iterating the process for future applications in the neural network. Despite having the same code as the cells before it (only change being that I excluded previous function definitions) the percolate_sim function only generates the first frame of the simulation. This is troubling given that the same lines, outside of a function produce the simulation with no issue.

**Comment by mcddanielle** [comment]
You probably want to try dividing up the animate call from the physics calls.  
[](https://www.numfys.net/howto/animations/)

the call to 
`anim = animation.FuncAnimation(fig, animate, init_func=init, frames=Nt, interval=20, blit=True)`
or your version of it implies iteration, and you're somehow not iterating (or not seeing the interaction) when you place it in a subroutine.
